export const chartConfigs = [
  {
    id: "grafico1",
    endpoint: "http://127.0.0.1:5000/api/grafico1",
    title: "Distribuição de Vendas por Loja",
    type: "bar" as "bar",
    xKey: "tipo_do_produto",
    yKey: "contagem",
    cor: "",
  },
  {
    id: "grafico2",
    endpoint: "http://127.0.0.1:5000/api/grafico2",
    title: "Distribuição de Vendas por Produto",
    type: "bar" as "bar",
    xKey: "loja",
    yKey: "contagem",
    cor: "",
  },
  {
    id: "grafico3",
    endpoint: "http://127.0.0.1:5000/api/grafico3",
    title: "Valor Total de Venda por Tipo de Produto",
    type: "bar" as "bar",
    xKey: "tipo_do_produto",
    yKey: "valor_total_venda",
    cor: "",
  },
  {
    id: "grafico4",
    endpoint: "http://127.0.0.1:5000/api/grafico4",
    title: "Valor de Compra vs Valor de Venda",
    type: "scatter" as "scatter",
    xKey: "valor de compra",
    yKey: "valor de venda",
    cor: "tipo do produto",
  },
  {
    id: "grafico5",
    endpoint: "http://127.0.0.1:5000/api/grafico5",
    title: "Quantidade Comprada por Loja",
    type: "bar" as "bar",
    xKey: "loja",
    yKey: "quantidade_total",
    cor: "",
  },
  {
    id: "grafico6",
    endpoint: "http://127.0.0.1:5000/api/grafico6",
    title: "Tipos de Envio",
    type: "pie" as "pie",
    xKey: "tipo_envio",
    yKey: "contagem",
    cor: "",
  },
  {
    id: "grafico7",
    endpoint: "http://127.0.0.1:5000/api/grafico7",
    title: "Status de Entrega por Loja",
    type: "histogram" as "histogram", // Alterado para 'bar' em vez de 'histogram'
    xKey: "loja que comprou",
    yKey: "contagem",
    cor: "status de entrega", // cor por 'status da entrega'
  },
  {
    id: "grafico8",
    endpoint: "http://127.0.0.1:5000/api/grafico8",
    title: "Quantidade Comprada por Moeda Usada",
    type: "bar" as "bar",
    xKey: "moeda",
    yKey: "quantidade_total",
    cor: "",
  },
  {
    id: "grafico9",
    endpoint: "http://127.0.0.1:5000/api/grafico9",
    title: "Valor Total de Venda por Moeda",
    type: "bar" as "bar",
    xKey: "moeda",
    yKey: "valor_total_venda",
    cor: "",
  },
];
